"""Downloads of generated volumes / ZIP, and explicit deletion of a session's files."""
from __future__ import annotations

import re

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, PlainTextResponse

from ..services.job_manager import manager
from ..services.report_service import build_report_text
from ..services.session_store import store
from ..services.zip_service import build_zip
from ..utils.file_utils import read_json
from .volumes import get_job_or_404

router = APIRouter(prefix="/api", tags=["downloads"])
VOLUME_ID_RE = re.compile(r"^([a-f0-9]{32})-(\d{1,4})$")
NO_CACHE = {"Cache-Control": "no-store"}


def _finished_status(job):
    if manager.is_active(job.id):
        raise HTTPException(409, "The job is still processing.")
    status = read_json(job.dir / "status.json", default={}) or {}
    if status.get("state") != "completed":
        raise HTTPException(409, "No completed volumes are available for this job.")
    return status


@router.get("/download/{volume_id}")
def download_volume(volume_id: str):
    m = VOLUME_ID_RE.match(volume_id)
    if not m:
        raise HTTPException(404, "Unknown volume.")
    job = get_job_or_404(m.group(1))
    status = _finished_status(job)
    vol = next((v for v in status.get("volumes", []) if v["index"] == int(m.group(2))), None)
    if vol is None:
        raise HTTPException(404, "Unknown volume.")
    if vol.get("status") == "FAIL":
        raise HTTPException(409, "This volume failed validation and cannot be downloaded.")
    path = job.dir / "out" / vol["filename"]  # filename was generated by the server, never user input
    if not path.is_file():
        raise HTTPException(404, "The file is no longer available.")
    return FileResponse(path, media_type="application/pdf", filename=vol["filename"], headers=NO_CACHE)


@router.get("/download-zip/{job_id}")
def download_zip(job_id: str):
    job = get_job_or_404(job_id)
    status = _finished_status(job)
    summary = status.get("summary") or {}
    if not summary.get("ready"):
        raise HTTPException(409, "Resolve all volumes that exceed the size limit (or failed validation) first.")
    spec = read_json(job.dir / "job.json")
    files = [(job.dir / "out" / v["filename"], v["filename"]) for v in status["volumes"]]
    if not all(p.is_file() for p, _ in files):
        raise HTTPException(404, "Some files are no longer available. Please generate again.")
    zip_path = job.dir / "volumes.zip"
    status_mtime = (job.dir / "status.json").stat().st_mtime
    if not zip_path.exists() or zip_path.stat().st_mtime < status_mtime:
        build_zip(files, zip_path)  # volume PDFs only; the report is a separate optional download
    return FileResponse(zip_path, media_type="application/zip", filename=spec["zip_name"], headers=NO_CACHE)


@router.get("/report/{job_id}")
def report(job_id: str):
    job = get_job_or_404(job_id)
    status = _finished_status(job)
    spec = read_json(job.dir / "job.json")
    return PlainTextResponse(
        build_report_text(spec, status),
        headers={**NO_CACHE, "Content-Disposition": f'attachment; filename="{spec["client"]}_Validation_Report.txt"'},
    )


@router.delete("/documents/{document_id}")
def delete_document(document_id: str):
    try:
        rec = store.get_document(document_id)
    except Exception:  # noqa: BLE001
        return {"deleted": False}
    for job_id in rec.jobs:
        manager.cancel(job_id)
    return {"deleted": store.delete_document(document_id)}
